import os

YOUTUBE_CLIENT_ID = os.getenv("YOUTUBE_CLIENT_ID", "")
YOUTUBE_CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
YOUTUBE_REFRESH_TOKEN = os.getenv("YOUTUBE_REFRESH_TOKEN", "")

PINTEREST_TOKEN = os.getenv("PINTEREST_ACCESS_TOKEN", "")

SALES_API_KEY = os.getenv("SALES_API_KEY", "")
SALES_API_URL = os.getenv("SALES_API_URL", "")
